(defmemory :concept tuigo-design-goal-performance :source repo :tags (tuigo architecture performance) :body "tuigo's north star is to be best-in-class among Go TUI frameworks: neat and simple API surface, and lightspeed/responsive at runtime. This should bias every architectural decision in layout/renderer/reconciler toward minimal allocations, avoiding full-screen redraws (per-cell diff only changed cells, per STYLEGUIDE.md's pure-layer rules), and keeping the public API (TUIML: Box/Text/Fragment + functional options) small rather than feature-sprawling. When choosing between a simpler-but-slower approach and a faster-but-more-complex one in the render/diff path, prefer the faster one — performance is a stated product requirement here, not a nice-to-have. Simplicity applies to the API surface; the internals (layout, diffing) are allowed to be more intricate in service of speed.")
(defmemory :concept tuigo-design-philosophy-vcl-2026 :source repo :tags (tuigo architecture design-philosophy events state) :links ((concept tuigo-design-goal-performance)) :body "tuigo's explicit north star (user's words): \"has to be better than React but 2026! like TObject back in Borland days, best in class; with events, etc.\" This is a deliberate reference point, not just \"inspired by Ink\" — the user wants the Borland VCL/TObject era's event-driven, property-based component model as the architectural ideal, modernized for 2026, and explicitly positioned as superior to React's model, not just a Go clone of it.

What this means concretely for tuigo's architecture, going forward:

1. Skip React's central weakness on purpose. React needs virtual-DOM diffing + reconciliation because DOM mutation is expensive and the tree can be huge. A terminal screen is at most a few thousand cells. tuigo should NOT copy React's tree-reconciliation model just because Ink did — full rebuild + cell-level buffer diff (already implemented in renderer.Diff) is simpler AND faster at this problem scale. Reconciler-level Element-tree patching (PLAN.md's reconciler/ package) should only be added if profiling actually shows it's needed, not by default. This is the \"better than React, not just a Go React\" thesis.

2. VCL/TObject-style events, not flat-tree handler walices. Borland's VCL assigned strongly-typed event closures directly to a component's named event property (OnClick, OnKeyPress) with O(1) dispatch to the focused/owning component. tuigo's current MVP (see [[tuigo-mvp-v1-architecture]]) does a full O(n) DFS walk of the whole Element tree on every keystroke calling every matching handler — that's a placeholder, not the target architecture. Future direction: a focus concept (one active input receives key events; global handlers like Ctrl+C remain tree-wide) so dispatch approaches VCL's directness.

3. Per-component stable state, not one flat hook sequence. Current UseState implementation (state.go) uses a single global hookPos counter shared across the whole render — a known, documented MVP limitation, not the end state. VCL components each own their own fields (TObject instance state); the React hooks-by-call-order trick is itself a workaround for JS having no stable component instances. tuigo should eventually give each component invocation (keyed by Element.Key, like the reconciler already anticipates) its own hook storage, which is strictly more robust than either React's rule (\"hooks must be unconditional and in the same order\") or the current tuigo MVP.

4. Visual polish is a first-class requirement, not a byproduct. Direct user feedback after testing the first chat example: \"looks not very pretty but works.\" Functional correctness was not sufficient. Next iteration should invest in an actual design pass: 24-bit truecolor (most 2026 terminals support it) instead of 256-color palette indices, a considered spacing/color theme rather than ad hoc ColorFg/ColorBg calls per element, clean typographic rhythm (consistent padding scale, aligned columns), and text truncation with ellipsis instead of silent hard clipping. See [[tuigo-design-goal-performance]] for the parallel \"fast\" half of the \"best in class\" bar — this memory is the \"pretty\" and \"well-architected\" half.

5. \"Events, etc\" as an explicit ask — the event system (OnKey/OnSpecialKey/OnAnyKey in event.go) should keep growing toward a full VCL-like vocabulary (focus/blur, mouse events later, lifecycle events like OnMount) rather than staying minimal forever.")
(defmemory :concept tuigo-mvp-v1-architecture :source repo :tags (tuigo architecture handoff mvp) :links ((concept tuigo-design-philosophy-vcl-2026) (concept tuigo-design-goal-performance)) :body "Snapshot of the tuigo MVP built in the 2026-07-04 session, for handoff to whichever agent continues the work. Covers PLAN.md's steps 3-6 (layout/render path through basic events+hooks), stopping short of steps 7-8 (full hook robustness, timers, hardening).

Packages:
- types/ — Element, Style, Key/KeyHandler, all enums. Shared so layout/renderer/reconciler avoid an import cycle back to root.
- layout/ — pure flexbox (flexbox.go) + WrapText (wrap.go). Row/column, padding/margin/gap, explicit-or-intrinsic main-axis sizing, flex:1 default, ContentRect for border+padding reservation. Fully unit-tested.
- renderer/ — Cell/Buffer/Diff (buffer.go, cell.go) for minimal-repaint terminal writes; Draw (draw.go) resolves the text-style cascade and clips every node to its ancestors' content rect; Terminal (terminal.go) is the impure shell — golang.org/x/term raw mode, alt-screen, stdin key decoding (including a burst-detection trick for ESC sequences via bufio.Reader.Buffered()), SIGWINCH resize, and an SGR-state-tracking Flush that only re-emits cursor moves/style codes when they change.
- root (tuigo.go/state.go/event.go/node.go/style.go) — Render() app loop (single goroutine, panic-safe terminal restore via defer+recover), Ctx.UseState[T] hooks, OnKey/OnSpecialKey/OnAnyKey.
- reconciler/ — intentionally NOT implemented. Every frame does a full component-function call + full layout + full Draw; only the final cell buffer is diffed. This was a deliberate MVP simplification, later reinforced as the actual target architecture in [[tuigo-design-philosophy-vcl-2026]] (skip React-style tree reconciliation on purpose — cell diffing alone is enough at terminal scale).

Known, documented limitations (not bugs, but the known gap to the target architecture):
1. UseState hook storage is one flat sequence (appState.hookPos) shared by the whole component tree, not per-component-instance. Works only if every UseState call happens unconditionally in the same order every render.
2. Key dispatch (dispatchKey in tuigo.go) does a full O(n) DFS of the Element tree on every keystroke, invoking every matching handler — no focus concept yet.
3. No timers/async state updates — the render loop only reacts to keyCh/resizeCh, so e.g. a \"bot is typing...\" delay before an auto-reply isn't possible yet without adding a scheduler.
4. SIGWINCH-based resize only compiles on unix (no Windows resize handling).
5. Colors are 256-index xterm (types.Color / style.go named consts), not 24-bit truecolor.
6. Text wrapping only happens in column-direction layout; row-direction Text children get single-line intrinsic width (no wrap).

Example: _examples/chat/main.go (run via example-chat.sh) — iMessage-style bubble chat mock validating the whole pipeline end-to-end. User tested it live: \"looks not very pretty but works\" — functionally correct, needs a real visual design pass next (see [[tuigo-design-philosophy-vcl-2026]] point 4).")
(defmemory :concept tuigo-mvp-v1-architecture :source repo :tags (tuigo architecture handoff mvp) :links ((concept tuigo-design-philosophy-vcl-2026) (concept tuigo-design-goal-performance)) :body "Updated 2026-07-04 (second pass, concurrent with another agent). This supersedes the original snapshot's \"known limitations\" list — most have since been resolved.

Concurrently completed by another agent (following ARCHITECTURE.md/TODO.md exactly), verified building/passing tests as of this update:
- TODO item 1: per-component instance tree (state.go's `instance` struct, keyed by Element.Key/positional path, hooks moved off the flat sequence, pruning cancels timers on removal).
- TODO item 2: focus-based dispatch (Focusable(), Ctx.Focus/FocusNext/FocusPrev, Global() handler modifier, dispatchGlobalKey/dispatchFocusedKey in tuigo.go replacing the old full-tree-walk dispatchKey).
- TODO item 3: Ctx.After timer scheduling, routed through appState.timers channel into the render loop (concurrency-safe per ARCHITECTURE.md's contract).
- TODO item 4: 24-bit truecolor (types.Color gained RGB()/IsRGB()/RGB() accessor, a `Theme` struct in style.go, writeSGR emits 38;2/48;2 for RGB). **I found and fixed a real bug here**: RGB() built a positive int but IsRGB() checked `c < 0`, so RGB colors never registered as RGB and would've emitted garbage 256-color SGR codes. Fixed via an explicit `rgbFlag = 1<<24` bit instead of sign-checking; added types/style_test.go to guard the regression.
- TODO item 5: ellipsis truncation (Style.Truncate field, drawTextTruncate in renderer/draw.go).

My own additions this pass (independent of the above, minimal-footprint edits into tuigo.go/state.go to avoid colliding with the concurrent work):
- Mouse support: types.MouseEvent/MouseButton/MouseAction/MouseHandler, renderer/terminal.go refactored to a single stdin-reading goroutine demultiplexing into separate Keys()/Mouse() channels (avoids a data race from two goroutines reading one bufio.Reader), SGR mouse mode (1000/1006) enabled/disabled with the terminal lifecycle, OnClick/OnMouse/OnScroll options, dispatchMouse in tuigo.go hit-tests the last-computed layout.Node tree bubbling from innermost match outward.
- A widget layer (widgets.go, root package, pure composition over Box/Text — no new core primitives): Panel (titled bordered container), Divider, Badge, ProgressBar (careful about Width(0)-means-unset — omits zero-width segments rather than passing Width(0)), Spinner (pure, caller-driven frame counter), Clock (reads time.Now() live), Dialog (full-viewport-takeover modal via flex-spacer centering — NOT a real z-order overlay, tuigo has no compositing yet), Menu (dropdown/popup list, e.g. a \"/\" slash-command palette — occupies its own row in normal flow rather than floating). All covered by widgets_test.go.
- A ticker (time.NewTicker(1s)) added to Render's select loop so wall-clock-derived UI (the Clock widget) updates without needing a key/resize/mouse event; buffer-diff means a no-visual-change tick costs CPU only, not terminal writes.
- I also fixed a latent bug in the other agent's in-progress renderOnce: `app.rootInst.hookPos` wasn't reset to 0 before the discovery/temp component() pass, only before the real pass — caused hooks to leak-grow every frame. Fixed by resetting before both passes.
- _examples/chat/main.go rewired to use all of the above: header now has a Badge, Spinner, and right-aligned Clock; footer has a decorative ProgressBar; \"/\" opens a live-filtered Menu of slash commands (/help, /clear, /quit) that resizes the message-list area to make room; \"?\" (when input is empty) opens a Dialog-based help screen; mouse wheel scrolls message history via OnScroll. Reconciled with the other agent's concurrent InputBar-as-focusable-subcomponent refactor by keeping input state at the App root instead — the slash-menu feature needs the parent to see live input text to size the sibling message-list area, which a fully encapsulated child component can't provide; the input Box still carries WithKey(\"input\")+Focusable() so it has real identity once more of the tree adopts the focus system.

Remaining from TODO.md as of this update: item 6 (UseReducer), item 7 (row-direction text wrapping), item 8 (Windows resize), item 9 (tuigo.go/state.go test coverage — note dispatchMouse and the widgets now have their own tests, but the app-loop/dispatch-focus functions in tuigo.go still don't). Verify against TODO.md's acceptance criteria before marking any item done — this memory describes what code exists, not that every acceptance test has been written.")
(defmemory :concept tuigo-pip-overlay-mechanism :source repo :tags (tuigo architecture pip overlay) :links ((concept tuigo-mvp-v1-architecture) (concept tuigo-design-philosophy-vcl-2026)) :body "Added Picture-in-Picture support, since tuigo has no z-order/absolute-positioning in the layout tree (flow layout only, per ARCHITECTURE.md). Solution: a buffer-stamping escape hatch rather than extending the layout model.

- `renderer.Stamp(dst, src *Buffer, x, y int)` (renderer/overlay.go) — copies one Buffer's cells onto another at an offset, clipped via the existing `Buffer.Set`. Pure, tested (renderer/overlay_test.go covers offset copy, clipping past dst bounds, negative-offset clipping).
- `tuigo.Overlay{Element, X, Y}` + `Ctx.Overlay(el, x, y)` (overlay.go, appState gained `pendingOverlays []Overlay`) — a component calls `ctx.Overlay(...)` during its render (like UseState, call it unconditionally on renders where the panel should be visible, omit it otherwise). `Render`'s renderOnce (tuigo.go) clears `pendingOverlays` before the *real* component pass only (not the discovery/temp pass — same double-render-per-frame issue as hooks; clearing before only the real pass avoids double-registration), then after the main `renderer.Draw`, does an independent `layout.Layout`+`renderer.Draw` for each overlay's Element (sized by its own explicit Style.Width/Height — overlays have no parent to size them) and `Stamp`s the result onto the main buffer *before* `renderer.Diff` — so overlays participate in the normal cell-diff for free, no special-casing needed in Flush.

Demoed in _examples/chat with 3 simultaneous PiP panels: a streaming telemetry log (bottom-right), a stats meter with two ProgressBars (bottom-left), and a transient toast notification (top-right, dialog-styled, auto-expires). All three stay visible even when the main tree renders the full-viewport help Dialog, since Ctx.Overlay is called before the `if showHelp return` branch — demonstrates layering multiple floating panels together, not just one at a time.

Key trick worth remembering: the telemetry/stats data update via **elapsed wall-clock time checked on every render** (`if time.Since(lastTickAt) > threshold`), not via `Ctx.After` closures or a background goroutine. A self-rescheduling `ctx.After(d, tick)` closure would capture a stale snapshot of the accumulating slice/value at closure-creation time and never see later updates (Go closures capture variables by reference to their *enclosing scope*, but each render creates fresh local variables via UseState, so a long-lived recursive closure keeps referencing the first render's snapshot forever). Reading fresh state and conditionally mutating based on elapsed time, driven by renders that already happen every ~1s (the Clock ticker, see [[tuigo-mvp-v1-architecture]]) or on any key/mouse/resize event, sidesteps this entirely — no goroutine-safety concerns since it all runs on the single render-loop goroutine.")
(defmemory :concept tuigo-audio-asciiart-libs :source repo :tags (tuigo audio asciiart media) :links ((concept tuigo-pip-overlay-mechanism) (concept tuigo-mvp-v1-architecture)) :body "Two new standalone-style library packages added to the tuigo module (not separate Go modules — top-level importable packages, same pattern as layout/renderer per PLAN.md), based on prior art found in the sibling project ~/go/src/github.com/wildneuro/eee (its audio.go chirp-synth and ascii.go grayscale-ramp converter).

**audio/** (audio.go, beep.go): Play/PlayAsync shell out to platform-native players (afplay on macOS, paplay/aplay/ffplay on Linux, PowerShell Media.SoundPlayer on Windows) rather than linking a CGo audio backend — no C toolchain needed, matches STYLEGUIDE.md's pure→impure layering philosophy applied to a sibling library. Record shells out to ffmpeg (none of the 3 OSes ship a scriptable recorder) — requires ffmpeg on PATH, device names are OS-typical defaults (darwin \":0\", linux \"default\", windows \"audio=Microphone\") but not guaranteed on every machine; callers can override. Beep/GenerateChirpWAV port eee's pure-Go two-tone WAV synth (no external deps at all) for UI feedback sounds. Tested: WAV header/sample-count/fade correctness (pure), playCommand branch on current GOOS (impure but assertable).

**asciiart/** (asciiart.go): Decode (image.Decode wrapper) + Grid/GridFit (nearest-neighbor downsample to a [][]Pixel RGB grid, aspect-corrected in GridFit for terminal cells being ~2x taller than wide) + Render/RenderFile (the original grayscale-ramp \"@%#*+=-:. \" string renderer, kept for non-color terminals). Found and fixed a real bug while testing: pure-white input was truncating to the second-lightest ramp char ('.' instead of ' ') because 0.299+0.587+0.114 doesn't sum to exactly 1.0 in float64 — fixed with math.Round + clamp instead of int() truncation.

**Chat integration** (_examples/chat/media.go, wired into main.go's App()): a \"/music\" slash command opens two PiP overlays simultaneously (replacing the ambient telemetry/stats PiPs while open, since screen space is tight) — a Now Playing panel with 3 embedded tracks (go:embed assets/*.mp3, extracted to a temp file on first play since native players need a real path, not bytes) with prev/play-pause/next both keyboard (←/→/Esc, global-scoped) and mouse-clickable, and a Gallery panel cycling 2 embedded images every second via asciiart truecolor blocks. Each image \"pixel\" is its own single-rune Text Element with its own ColorFg (RGB) — a Text element carries one style for its whole string per STYLEGUIDE.md's cascade rule, so a color image needs one Element per cell, not one per row.

Real gap flagged during design, not fixed: tuigo has no component-unmount lifecycle yet, so a still-playing background audio process would survive the TUI closing via Ctrl+C. Worked around with a package-level `activeStop func()` in the chat example that `main()` calls via defer after `Render` returns — not a framework fix, just documented as a reason unmount hooks would be a good future TODO item.

Also fixed in this same pass (unrelated to audio/ascii but discovered while wiring keyboard/mouse for the PiPs): renderOnce in tuigo.go was unconditionally resetting `app.focusPath = \"\"` every render before recomputing the default, which silently undid both Tab/FocusNext cycling and any component-level Ctx.Focus() call every single frame — fixed to only reset when the current focus target is no longer in the fresh focusOrder.

Placeholder images note: the user pasted 2 photos in chat, but there's no tool available to write a pasted image to disk — generated 2 synthetic placeholder PNGs (assets/photo1.png, photo2.png) instead and told the user to drop their real photos in with the same filenames to swap them in.")
(defmemory :concept tuigo-chat-media-pip-polish-v2 :source repo :tags (tuigo pip media ui-polish) :links ((experience tuigo-pip-overlay-collision-bug) (concept tuigo-pip-overlay-mechanism)) :body "Second polish pass on the chat example's PiP media feature, done via a dispatched subagent + my own independent re-verification (found and fixed one regression the subagent introduced).

Subagent fixed: toast overlap (converted from a floating Ctx.Overlay to an inline flow banner between header/messages, same menuH/messagesH pattern the \"/\" command menu already used — guarantees zero overlap by construction instead of positioning luck), silent music (now auto-plays on \"/music\" instead of requiring a mouse click on ⏯), gallery had no manual nav (main.go/media.go signature mismatch meant it didn't even compile — fixed the call site, wired Up/Down keys), added a Winamp-style equalizer+seekbar to the music panel (pure per-render-seeded animation, no goroutines — same elapsed-time-tick pattern as telemetry/stats), rounded borders, and a theme switch (`/theme` command toggling DarkTheme/LightTheme via the newly-added `tuigo.SetTheme`).

Bug I found in my own re-verification (subagent's own tmux checks didn't catch it): the drop-shadow overlay was offset (+1,+1) from each panel with the SAME height as the panel, so for panels anchored flush against `pipBottom` (Stats, Telemetry — see [[tuigo-pip-overlay-collision-bug]] for why that anchor point exists), the shadow's bottom edge landed 1 row INSIDE the input box, corrupting its border. Fixed by adding a `maxY` param to `shadowOverlay` that clamps the shadow's height so it never crosses `pipBottom` — same \"clamp against pipBottom\" pattern as the earlier gallery-height bug, this overlay system has now hit this exact class of bug three times (menu/PiP collision, music/gallery overlap, shadow overflow) — worth remembering as the standing risk with `Ctx.Overlay`: every overlay's geometry must be explicitly checked against the safe-area boundary, nothing does it automatically.

Also, per direct user request, upgraded the shadow from a flat RGB(20,20,20) color-filled box to actual dithered `▒` (medium shade) glyphs — the authentic Turbo Vision/Borland-era window-shadow look, not a modern soft-shadow approximation — and gave the shared `Panel` widget (widgets.go, core library, not chat-specific) a real full-width colored title bar (Box with ColorBg(Theme.Accent) wrapping the title Text) instead of a plain bold text line. Found in the process: a standalone Text element's ColorBg only paints behind its own characters (renderer/draw.go's drawText doesn't call fillBackground), so a \"colored bar spanning the full row\" requires wrapping in a Box — this is a real, non-obvious renderer behavior worth remembering for any future \"highlight a full row\" styling.")
(defmemory :concept tuigo-animation-pattern :source repo :tags (tuigo animation pip overlay) :links ((experience tuigo-chat-pip-layout-v3) (experience tuigo-pip-overlay-collision-bug)) :body "Added animated UI to tuigo per user request (\"dynamically changing divs, e.g. right drawer open, slides in\"). No changes to the render loop or a new \"animation system\" in core — this is entirely an application-level pattern built from three things tuigo already had:

1. **animation.go** (new, core library, tested): `Lerp(a,b,t)`, `Clamp01(t)`, `EaseOutCubic(t)`, `EaseInCubic(t)` — pure math, genuinely reusable by any app wanting motion via the overlay system. Deliberately kept tiny; ARCHITECTURE.md is explicit that Render only re-renders on discrete events + a 1s ticker, so smooth motion needs the app to drive it.

2. **The re-render-frequency problem and its fix**: a 250ms slide animation needs way more than 1-2 renders to look smooth, but Render's default cadence (input events + 1Hz ticker) won't provide that on its own. Fix: while animating, call `ctx.After(20*time.Millisecond, func() {})` — an EMPTY callback. This works because `tuigo.go`'s select loop unconditionally calls `renderOnce()` after ANY timer fires, regardless of what the callback did — so an empty closure is enough to force an extra render, with zero risk of the stale-closure trap that would come from trying to accumulate/read state across ticks (see the telemetry/stats elapsed-time-tick comments in _examples/chat/main.go for that trap in detail — this animation approach deliberately avoids it by not depending on the closure remembering anything; each render independently decides \"am I still animating, should I schedule another tick\").

3. **Ctx.Overlay with a computed, time-varying X** — `_examples/chat`'s new `/info` command opens a right-side drawer: `x := int(tuigo.Lerp(float64(width), float64(restX), tuigo.EaseOutCubic(progress)))`, where progress is `Clamp01(elapsed/duration)` tracked via a `UseState` timestamp set once when the drawer opens (same \"run once\" pattern as focusInit/mediaAutoStarted elsewhere in that file).

Real bug caught during verification (same recurring class as [[tuigo-chat-pip-layout-v3]] and [[tuigo-pip-overlay-collision-bug]]): the drawer's rest X position (`width - drawerW - 1`) landed in the exact same column as the existing Telemetry/Stats column (`width - 30`), so both rendered simultaneously and overlapped. Fixed by hiding Telemetry/Stats while the info drawer is open/animating, same \"don't draw two things in the same space, hide one\" policy already established for the music/gallery vs stats collision. This overlay model has now hit the \"two independently-positioned overlays claim the same space\" bug at least four times across this session — worth treating as a checklist item (list every currently-visible overlay's rect, check for pairwise overlap) any time a new overlay is added, rather than trusting visual inspection alone.

Closing is intentionally NOT animated (asymmetric slide-in/instant-close) — documented as a scope cut, not an oversight, since animating both directions needs a second timestamp+direction and canceling an in-flight open transition if closed mid-slide.")
